FlaskWebProject/Exam/posts/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, TextAreaField
from wtforms.validators import DataRequired


class PostForm(FlaskForm):
    title = StringField('Title', validators=[DataRequired()])
    content = TextAreaField('Content', validators=[DataRequired()])
    submit = SubmitField('Post')

FlaskWebProject/Exam/posts/routes.py
from flask import (render_template, url_for, flash,
                   redirect, request, abort, Blueprint)
from flask_login import current_user, login_required
from Exam import db
from Exam.models import Post
from Exam.posts.forms import PostForm

posts = Blueprint('posts', __name__)


@posts.route("/post/new", methods=['GET', 'POST'])
@login_required
def new_post():
    form = PostForm()
    if form.validate_on_submit():
        post = Post(title=form.title.data, content=form.content.data, author=current_user)
        db.session.add(post)
        db.session.commit()
        flash('Your post has been created!', 'success')
        return redirect(url_for('main.home'))
    return render_template('create_post.html', title='New Post',
                           form=form, legend='New Post')


@posts.route("/post/<int:post_id>")
def post(post_id):
    post = Post.query.get_or_404(post_id)
    return render_template('post.html', title=post.title, post=post)


@posts.route("/post/<int:post_id>/update", methods=['GET', 'POST'])
@login_required
def update_post(post_id):
    post = Post.query.get_or_404(post_id)
    if post.author != current_user:
        abort(403)
    form = PostForm()
    if form.validate_on_submit():
        post.title = form.title.data
        post.content = form.content.data
        db.session.commit()
        flash('Your post has been updated!', 'success')
        return redirect(url_for('posts.post', post_id=post.id))
    elif request.method == 'GET':
        form.title.data = post.title
        form.content.data = post.content
    return render_template('create_post.html', title='Update Post',
                           form=form, legend='Update Post')


@posts.route("/post/<int:post_id>/delete", methods=['POST'])
@login_required
def delete_post(post_id):
    post = Post.query.get_or_404(post_id)
    if post.author != current_user:
        abort(403)
    db.session.delete(post)
    db.session.commit()
    flash('Your post has been deleted!', 'success')
    return redirect(url_for('main.home'))

FlaskWebProject/Exam/users/routes.py
from flask import render_template, url_for, flash, redirect, request, Blueprint
from flask_login import login_user, current_user, logout_user, login_required
from Exam import db, bcrypt
from Exam.models import User, Post
from Exam.users.forms import (RegistrationForm, LoginForm, UpdateAccountForm,
                                   RequestResetForm, ResetPasswordForm)
from Exam.users.utils import save_picture, send_reset_email

users = Blueprint('users', __name__)


@users.route("/register", methods=['GET', 'POST'])
def register():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = RegistrationForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user = User(username=form.username.data, email=form.email.data, password=hashed_password)
        db.session.add(user)
        db.session.commit()
        flash('Your account has been created! You are now able to log in', 'success')
        return redirect(url_for('users.login'))
    return render_template('register.html', title='Register', form=form)


@users.route("/login", methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user and bcrypt.check_password_hash(user.password, form.password.data):
            login_user(user, remember=form.remember.data)
            next_page = request.args.get('next')
            return redirect(next_page) if next_page else redirect(url_for('main.home'))
        else:
            flash('Login Unsuccessful. Please check email and password', 'danger')
    return render_template('login.html', title='Login', form=form)


@users.route("/logout")
def logout():
    logout_user()
    return redirect(url_for('main.home'))


@users.route("/account", methods=['GET', 'POST'])
@login_required
def account():
    form = UpdateAccountForm()
    if form.validate_on_submit():
        if form.picture.data:
            picture_file = save_picture(form.picture.data)
            current_user.image_file = picture_file
        current_user.username = form.username.data
        current_user.email = form.email.data
        db.session.commit()
        flash('Your account has been updated!', 'success')
        return redirect(url_for('users.account'))
    elif request.method == 'GET':
        form.username.data = current_user.username
        form.email.data = current_user.email
    image_file = url_for('static', filename='profile_pics/' + current_user.image_file)
    return render_template('account.html', title='Account',
                           image_file=image_file, form=form)


@users.route("/user/<string:username>")
def user_posts(username):
    page = request.args.get('page', 1, type=int)
    user = User.query.filter_by(username=username).first_or_404()
    posts = Post.query.filter_by(author=user)\
        .order_by(Post.date_posted.desc())\
        .paginate(page=page, per_page=5)
    return render_template('user_posts.html', posts=posts, user=user)


@users.route("/reset_password", methods=['GET', 'POST'])
def reset_request():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = RequestResetForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        send_reset_email(user)
        flash('An email has been sent with instructions to reset your password.', 'info')
        return redirect(url_for('users.login'))
    return render_template('reset_request.html', title='Reset Password', form=form)


@users.route("/reset_password/<token>", methods=['GET', 'POST'])
def reset_token(token):
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    user = User.verify_reset_token(token)
    if user is None:
        flash('That is an invalid or expired token', 'warning')
        return redirect(url_for('users.reset_request'))
    form = ResetPasswordForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user.password = hashed_password
        db.session.commit()
        flash('Your password has been updated! You are now able to log in', 'success')
        return redirect(url_for('users.login'))
    return render_template('reset_token.html', title='Reset Password', form=form)

FlaskWebProject/Exam/templates/about.html
{% extends "layout.html" %}
{% block content %}
<div class="contentTitle">
    <h1>About GATE</a></h1>
</div>
<div style="margin-left: 0px; width: 950px;" class="contentText">
    <p align="justify">Graduate Aptitude Test in Engineering (GATE) is basically an examination on the comprehensive understanding of the candidates in various undergraduate subjects in Engineering/Technology/ Architecture and post-graduate level subjects in Science. GATE 2020 will be conducted for 25 subjects (also referred to as “papers”) and it would be distributed over 1st, 2nd, 8th & 9th of February 2020. The GATE examination centres are spread in different cities across India, as well as, in six cities outside India. The examination would be purely a Computer Based Test (CBT). <br /><br />The GATE score would reflect the relative performance level of the candidate in a particular subject, which is quantified based on the several years of examination data. Note that the GATE 2020 score is valid for <strong>THREE YEARS</strong> from the date of announcement of the results.</p>
</div>
{% endblock content %}

FlaskWebProject/Exam/templates/account.html
{% extends "layout.html" %}
{% block content %}
<div class="content-section">
    <div class="media">
        <img class="rounded-circle account-img" src="{{ image_file }}" height="72" width="100">
        <div class="media-body">
            <h2 class="account-heading">{{ current_user.username }}</h2>
            <p class="text-secondary">{{ current_user.email }}</p>
        </div>
    </div>
    <form method="POST" action="" enctype="multipart/form-data">
        {{ form.hidden_tag() }}
        <fieldset class="form-group">
            <legend class="border-bottom mb-4">Account Info</legend>
            <div class="form-group">
                {{ form.username.label(class="form-control-label") }}

                {% if form.username.errors %}
                {{ form.username(class="form-control form-control-lg is-invalid") }}
                <div class="invalid-feedback">
                    {% for error in form.username.errors %}
                    <span>{{ error }}</span>
                    {% endfor %}
                </div>
                {% else %}
                {{ form.username(class="form-control form-control-lg") }}
                {% endif %}
            </div>
            <div class="form-group">
                {{ form.email.label(class="form-control-label") }}
                {% if form.email.errors %}
                {{ form.email(class="form-control form-control-lg is-invalid") }}
                <div class="invalid-feedback">
                    {% for error in form.email.errors %}
                    <span>{{ error }}</span>
                    {% endfor %}
                </div>
                {% else %}
                {{ form.email(class="form-control form-control-lg") }}
                {% endif %}
            </div>
            <div class="form-group">
                {{ form.picture.label() }}
                {{ form.picture(class="form-control-file") }}
                {% if form.picture.errors %}
                {% for error in form.picture.errors %}
                <span class="text-danger">{{ error }}</span></br>
                {% endfor %}
                {% endif %}
            </div>
        </fieldset>
        <div class="form-group">
            {{ form.submit(class="btn btn-outline-info") }}
        </div>
    </form>
</div>
{% endblock content %}

FlaskWebProject/Exam/templates/contactus.html
{% extends "layout.html" %}
{% block content %}
<div class="contentTitle">
    <h1>Contact Us</h1>
</div>
<div style="margin-left: 0px; width: 950px;" class="contentText">
    <br /><br />
    <table id="gateTable" width="95%">
        <tr>
            <th><p><strong>Zone</strong></p></td>
            <th>
                <strong>
                    Contact Address
                    </p>
                </strong></td>
            <th>
                <strong>
                    Phone Number
                    </p>
                </strong></td>
            <th>
                <strong>
                    e-mail Id
                    </p>
                </strong></td>
        </tr>
        <tr>
            <td><p>1</p></td>
            <td>
                <p>
                    Chairman, GATE<br />
                    Indian Institute of Science,<br />
                    Bengaluru 560 012
                </p>
            </td>
            <td>
                080-22932392<br />
                080-23601227</p>
            </td>
            <td>gate@gate.iisc.ac.in</p></td>
        </tr>
        <tr>
            <td><p>2</p></td>
            <td>
                <p>
                    Chairman, GATE<br />
                    Indian Institute of Technology Bombay, <br />Powai, Mumbai 400 076
                </p>
            </td>
            <td>022-25767068</p></td>
            <td>gateoffice@iitb.ac.in</p></td>
        </tr>
        <tr>
            <td><p>3</p></td>
            <td>
                <p>
                    Chairman, GATE<br />
                    Indian Institute of Technology Delhi, <br />Hauz Khas, New Delhi 110 016
                </p>
            </td>
            <td>
                011-26591750<br />011-26596137<br />
                011-26591749</p>
            </td>
            <td>chrgate@admin.iitd.ac.in</p></td>
        </tr>
        <tr>
            <td><p>4</p></td>
            <td>
                <p>
                    Chairman, GATE<br />
                    Indian Institute of Technology Guwahati,<br />
                    Guwahati 781 039
                </p>
            </td>
            <td>
                0361-2582751<br />
                0361-2582755</p>
            </td>
            <td>gate@iitg.ac.in   </p></td>
        </tr>
        <tr>
            <td><p>5</p></td>
            <td>
                <p>
                    Chairman, GATE<br />
                    Indian Institute of Technology Kanpur,<br />
                    Kanpur 208 016
                </p>
            </td>
            <td>0512-2597412</p></td>
            <td>gate@iitk.ac.in</p></td>
        </tr>
        <tr>
            <td><p>6</p></td>
            <td>
                <p>
                    Chairman, GATE<br />
                    Indian Institute of Technology Kharagpur, <br />Kharagpur 721 302
                </p>
            </td>
            <td>
                03222-282091<br />
                03222-282095</p>
            </td>
            <td>gate@adm.iitkgp.ac.in </p></td>
        </tr>
        <tr>
            <td><p>7</p></td>
            <td>
                <p>
                    Chairman, GATE<br />
                    Indian Institute of Technology Madras,<br />
                    Chennai 600 036
                </p>
            </td>
            <td>044-22578200</p></td>
            <td>gate@iitm.ac.in</p></td>
        </tr>
        <tr>
            <td><p>8</p></td>
            <td>
                <p>
                    Chairman, GATE<br />
                    Indian Institute of Technology Roorkee,<br />
                    Roorkee 247 667
                </p>
            </td>
            <td>01332-284531</p></td>
            <td>gate@iitr.ac.in</p></td>
        </tr>
    </table>
    <p>&nbsp;</p>
</div>



{% endblock content %}

FlaskWebProject/Exam/templates/create_post.html
{% extends "layout.html" %}
{% block content %}
<div class="content-section">
    <form method="POST" action="">
        {{ form.hidden_tag() }}
        <fieldset class="form-group">
            <legend class="border-bottom mb-4">{{ legend }}</legend>
            <div class="form-group">
                {{ form.title.label(class="form-control-label") }}
                {% if form.title.errors %}
                    {{ form.title(class="form-control form-control-lg is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in form.title.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                {% else %}
                    {{ form.title(class="form-control form-control-lg") }}
                {% endif %}
            </div>
            <div class="form-group">
                {{ form.content.label(class="form-control-label") }}
                    {% if form.content.errors %}
                    {{ form.content(class="form-control form-control-lg is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in form.content.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                {% else %}
                    {{ form.content(class="form-control form-control-lg") }}
                {% endif %}
            </div>
        </fieldset>
        <div class="form-group">
            {{ form.submit(class="btn btn-outline-info") }}
        </div>
    </form>
</div>
{% endblock content %}

FlaskWebProject/Exam/templates/home.html
{% extends "layout.html" %}
{% block content %}
    {% for post in posts.items %}
<article class="media content-section">
    <img class="rounded-circle article-img" src="{{ url_for('static', filename='profile_pics/' + post.author.image_file) }}" height="72" width="100">
    <div class="media-body">
        <div class="article-metadata">
            <a class="mr-2" href="{{ url_for('users.user_posts', username=post.author.username) }}">{{ post.author.username }}</a>
            <small class="text-muted">{{ post.date_posted.strftime('%Y-%m-%d') }}</small>
        </div>
        <h2><a class="article-title" href="{{ url_for('posts.post', post_id=post.id) }}">{{ post.title }}</a></h2>
        <p class="article-content">{{ post.content }}</p>
    </div>
</article>
    {% endfor %}
    {% for page_num in posts.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
      {% if page_num %}
        {% if posts.page == page_num %}
<a class="btn btn-info mb-4" href="{{ url_for('main.home', page=page_num) }}">{{ page_num }}</a>
        {% else %}
<a class="btn btn-outline-info mb-4" href="{{ url_for('main.home', page=page_num) }}">{{ page_num }}</a>
        {% endif %}
      {% else %}
        ...
      {% endif %}
    {% endfor %}
{% endblock content %}
<main role="article" class="container">
        <div class="col-md-4">
            <div class="content-section">
                <h3>Our Sidebar</h3>
                <p class='text-muted'>
                    You can put any information here you'd like.
                    <ul class="list-group">
                        <li class="list-group-item list-group-item-light">Latest Posts</li>
                        <li class="list-group-item list-group-item-light">Announcements</li>
                        <li class="list-group-item list-group-item-light">Calendar</li>
                        <li class="list-group-item list-group-item-light">etc</li>
                    </ul>
                </p>
            </div>
        </div>
</main>

FlaskWebProject/Exam/templates/importantdates.html
{% extends "layout.html" %}
{% block content %}
        <div class="contentTitle">
            <h1> Important Dates</h1>
        </div>
        <div style="margin-left: 0px; width: 950px;" class="contentText">
            <br><br />
            <table id="gateTable" border="1" cellspacing="0" cellpadding="2" width="95%">
                <tr>
                    <th><p><strong>Activity</strong></p></td>
                    <th><p align="center"><strong>Day</strong></p></td>
                    <th><p><strong>Date</strong></p></td>
                </tr>
                <tr>
                    <td width="59%"><p>GATE Online Application Processing System (GOAPS) Website Opens</p></td>
                    <td width="14%"><p align="center">Tuesday</p></td>
                    <td width="26%"><p>3rd September 2019</p></td>
                </tr>
                <tr>
                    <td width="59%"><p>Closing Date for Submission of (Online) Application (through Website)  </p></td>
                    <td width="14%"><p align="center">Saturday</p></td>
                    <td width="26%"><p align="center">28th &nbsp;September 2019</p></td>
                </tr>
                <tr>
                    <td width="59%"><p>Extended Closing Date for Submission of (Online) Application (through Website) </p></td>
                    <td width="14%"><p>Saturday</p></td>
                    <td width="26%"><p>5th October 2019</p></td>
                </tr>
                <tr>
                    <td width="59%"><p>Last Date for Requesting Change of Examination City (an additional fee will be applicable)</p></td>
                    <td width="14%"><p align="center">Monday</p></td>
                    <td width="26%"><p align="center">25th November 2019</p></td>
                </tr>
                <tr>
                    <td width="59%"><p>Admit Card will be available in the Online Application Portal (for printing)</p></td>
                    <td width="14%"><p align="center">Friday</p></td>
                    <td width="26%"><p align="center">3rd&nbsp; &nbsp;January 2020</p></td>
                </tr>
                <tr>
                    <td width="59%">
                        <p>
                            GATE 2020 Examination<br />
                            Forenoon: 9:30 AM to 12:30 PM (Tentative)<br />
                            Afternoon: 2:30 PM to 5:30 PM (Tentative)
                        </p>
                    </td>
                    <td width="14%">
                        <p align="center">
                            Saturday<br />
                            Sunday<br />
                            Saturday<br />
                            Sunday
                        </p>
                    </td>
                    <td width="26%">
                        <p align="center">
                            1st February 2020<br />
                            2nd February 2020<br />
                            8th February 2020<br />
                            9th February 2020
                        </p>
                    </td>
                </tr>
                <tr>
                    <td width="59%"><p>Announcement of the Results in the Online Application Portal</p></td>
                    <td width="14%"><p align="center">Monday</p></td>
                    <td width="26%"><p align="center">16th March 2020</p></td>
                </tr>
            </table>

        </div>

        <p>&nbsp;</p>

        <div id="footer">Copyright : GATE 2020, IIT Delhi</div>



{% endblock content %}

FlaskWebProject/Exam/templates/login.html
{% extends "layout.html" %}
{% block content %}
<div class="content-section">
    <form method="POST" action="">
        {{ form.hidden_tag() }}
        <fieldset class="form-group">
            <legend class="border-bottom mb-4">Log In</legend>
            <div class="form-group">
                {{ form.email.label(class="form-control-label") }}
                {% if form.email.errors %}
                {{ form.email(class="form-control form-control-lg is-invalid") }}
                <div class="invalid-feedback">
                    {% for error in form.email.errors %}
                    <span>{{ error }}</span>
                    {% endfor %}
                </div>
                {% else %}
                {{ form.email(class="form-control form-control-lg") }}
                {% endif %}
            </div>
            <div class="form-group">
                {{ form.password.label(class="form-control-label") }}
                {% if form.password.errors %}
                {{ form.password(class="form-control form-control-lg is-invalid") }}
                <div class="invalid-feedback">
                    {% for error in form.password.errors %}
                    <span>{{ error }}</span>
                    {% endfor %}
                </div>
                {% else %}
                {{ form.password(class="form-control form-control-lg") }}
                {% endif %}
            </div>
            <div class="form-check">
                {{ form.remember(class="form-check-input") }}
                {{ form.remember.label(class="form-check-label") }}
            </div>
        </fieldset>
        <div class="form-group">
            {{ form.submit(class="btn btn-outline-info") }}
            <small class="text-muted ml-2">
                <a href="{{ url_for('users.reset_request') }}">Forgot Password?</a>
            </small>
        </div>
    </form>
</div>
<div class="border-top pt-3">
    <small class="text-muted">
        Need An Account? <a class="ml-2" href="{{ url_for('users.register') }}">Sign Up Now</a>
    </small>
</div>
{% endblock content %}

FlaskWebProject/Exam/templates/post.html
{% extends "layout.html" %}
{% block content %}
<article class="media content-section">
    <img class="rounded-circle article-img" src="{{ url_for('static', filename='profile_pics/' + post.author.image_file) }}">
    <div class="media-body">
        <div class="article-metadata">
            <a class="mr-2" href="{{ url_for('users.user_posts', username=post.author.username) }}">{{ post.author.username }}</a>
            <small class="text-muted">{{ post.date_posted.strftime('%Y-%m-%d') }}</small>
            {% if post.author == current_user %}
            <div>
                <a class="btn btn-secondary btn-sm mt-1 mb-1" href="{{ url_for('posts.update_post', post_id=post.id) }}">Update</a>
                <button type="button" class="btn btn-danger btn-sm m-1" data-toggle="modal" data-target="#deleteModal">Delete</button>
            </div>
            {% endif %}
        </div>
        <h2 class="article-title">{{ post.title }}</h2>
        <p class="article-content">{{ post.content }}</p>
    </div>
</article>
<!-- Modal -->
<div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="deleteModalLabel">Delete Post?</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                <form action="{{ url_for('posts.delete_post', post_id=post.id) }}" method="POST">
                    <input class="btn btn-danger" type="submit" value="Delete">
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

FlaskWebProject/Exam/templates/register.html
{% extends "layout.html" %}
{% block content %}
<div class="content-section">
    <form method="POST" action="">
        {{ form.hidden_tag() }}
        <fieldset class="form-group">
            <legend class="border-bottom mb-4">Join Today</legend>
            <div class="form-group">
                {{ form.username.label(class="form-control-label") }}

                {% if form.username.errors %}
                {{ form.username(class="form-control form-control-lg is-invalid") }}
                <div class="invalid-feedback">
                    {% for error in form.username.errors %}
                    <span>{{ error }}</span>
                    {% endfor %}
                </div>
                {% else %}
                {{ form.username(class="form-control form-control-lg") }}
                {% endif %}
            </div>
            <div class="form-group">
                {{ form.email.label(class="form-control-label") }}
                {% if form.email.errors %}
                {{ form.email(class="form-control form-control-lg is-invalid") }}
                <div class="invalid-feedback">
                    {% for error in form.email.errors %}
                    <span>{{ error }}</span>
                    {% endfor %}
                </div>
                {% else %}
                {{ form.email(class="form-control form-control-lg") }}
                {% endif %}
            </div>
            <div class="form-group">
                {{ form.password.label(class="form-control-label") }}
                {% if form.password.errors %}
                {{ form.password(class="form-control form-control-lg is-invalid") }}
                <div class="invalid-feedback">
                    {% for error in form.password.errors %}
                    <span>{{ error }}</span>
                    {% endfor %}
                </div>
                {% else %}
                {{ form.password(class="form-control form-control-lg") }}
                {% endif %}
            </div>
            <div class="form-group">
                {{ form.confirm_password.label(class="form-control-label") }}
                {% if form.confirm_password.errors %}
                {{ form.confirm_password(class="form-control form-control-lg is-invalid") }}
                <div class="invalid-feedback">
                    {% for error in form.confirm_password.errors %}
                    <span>{{ error }}</span>
                    {% endfor %}
                </div>
                {% else %}
                {{ form.confirm_password(class="form-control form-control-lg") }}
                {% endif %}
            </div>
        </fieldset>
        <div class="form-group">
            {{ form.submit(class="btn btn-outline-info") }}
        </div>
    </form>
</div>
<div class="border-top pt-3">
    <small class="text-muted">
        Already Have An Account? <a class="ml-2" href="{{ url_for('users.login') }}">Sign In</a>
    </small>
</div>
{% endblock content %}

FlaskWebProject/Exam/templates/reset_request.html
{% extends "layout.html" %}
{% block content %}
<div class="content-section">
    <form method="POST" action="">
        {{ form.hidden_tag() }}
        <fieldset class="form-group">
            <legend class="border-bottom mb-4">Reset Password</legend>
            <div class="form-group">
                {{ form.email.label(class="form-control-label") }}
                {% if form.email.errors %}
                {{ form.email(class="form-control form-control-lg is-invalid") }}
                <div class="invalid-feedback">
                    {% for error in form.email.errors %}
                    <span>{{ error }}</span>
                    {% endfor %}
                </div>
                {% else %}
                {{ form.email(class="form-control form-control-lg") }}
                {% endif %}
            </div>
        </fieldset>
        <div class="form-group">
            {{ form.submit(class="btn btn-outline-info") }}
        </div>
    </form>
</div>
{% endblock content %}

FlaskWebProject/Exam/templates/reset_token.html
{% extends "layout.html" %}
{% block content %}
<div class="content-section">
    <form method="POST" action="">
        {{ form.hidden_tag() }}
        <fieldset class="form-group">
            <legend class="border-bottom mb-4">Reset Password</legend>
            <div class="form-group">
                {{ form.password.label(class="form-control-label") }}
                {% if form.password.errors %}
                {{ form.password(class="form-control form-control-lg is-invalid") }}
                <div class="invalid-feedback">
                    {% for error in form.password.errors %}
                    <span>{{ error }}</span>
                    {% endfor %}
                </div>
                {% else %}
                {{ form.password(class="form-control form-control-lg") }}
                {% endif %}
            </div>
            <div class="form-group">
                {{ form.confirm_password.label(class="form-control-label") }}
                {% if form.confirm_password.errors %}
                {{ form.confirm_password(class="form-control form-control-lg is-invalid") }}
                <div class="invalid-feedback">
                    {% for error in form.confirm_password.errors %}
                    <span>{{ error }}</span>
                    {% endfor %}
                </div>
                {% else %}
                {{ form.confirm_password(class="form-control form-control-lg") }}
                {% endif %}
            </div>
        </fieldset>
        <div class="form-group">
            {{ form.submit(class="btn btn-outline-info") }}
        </div>
    </form>
</div>
{% endblock content %}